import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { NavBar } from "./navbar";
import PlaybackBar from "./PlaybackBar";
import getDB from "@/lib/db";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const db = getDB();

const randomSongs = await db
  .selectFrom("songs")
  .innerJoin("albums", "albums.id", "songs.album_id")
  .innerJoin("authors", "authors.id", "albums.author_id")
  .limit(5)
  .select(["songs.id", "songs.name", "songs.duration", "authors.name as author"])
  .execute();



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        <NavBar />
        <div className="pt-15">
          {children}
        </div>

        <div className="h-40 fixed bottom-0 left-0 right-0 text-center bg-base-100">
          <PlaybackBar songs={randomSongs} />
        </div>
      </body>
    </html>
  );
}
